### ISSUE TITLE
FRP: find and replace all any

### ISSUE THREAD

**Issue by Majorfi** [Majorfi/NFTreasury#50]
`any` are great way to reduce dev time. Now that it's prod, find them and replace them with proper typing

**Comment by orrgoren** [comment]
Hi there! I'd love to work on that.

**Comment by igorlourenco** [comment]
is anyone working on that?

**Comment by MarcoWorms** [comment]
@igorlourenco last comments seems to have almost 2 months, I think it's good to go!!

**Comment by karelianpie** [comment]
Let's close this :) PR up for review https://github.com/yearn/NFTreasury/pull/59

/cc @Majorfi @MarcoWorms
