### ISSUE TITLE
FRP: replace subgraph

### ISSUE THREAD

**Issue by Majorfi** [Majorfi/NFTreasury#51]
Because of some issue with Yearn's subgraph we had to use Messari's subgraph.
Once [this](https://thegraph.com/hosted-service/subgraph/rareweasel/yearn-vaults-v2-subgraph-mainnet) one is sync again, replace the subgraph [calls](https://github.com/yearn/NFTreasury/blob/next/contexts/useYearn.tsx#L61-L99) in `useYearn` to use it in order to build the graph in the `/treasury` page

**Comment by karelianpie** [comment]
@Majorfi is this issue still valid?

**Comment by Majorfi** [comment]
Yes ser!

**Comment by karelianpie** [comment]
Noice, @Majorfi please assign it to me and I'll have a look
